apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: identidock
spec:
  selector:
    name: redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
