apiVersion: v1
kind: Service
metadata:
  name: dnmonster
  labels:
    name: dnmonster
    app: identidock
spec:
  selector:
    name: dnmonster
  type: ClusterIP
  ports:
    - name: dnmonster
      port: 8080
      targetPort: 8080
