apiVersion: v1
kind: Pod
metadata:
  name: dnmonster
  labels:
    name: dnmonster
    app: identidock
spec: 
  containers: 
    - image: amouat/dnmonster:1.0
      name: dnmonster
      ports: 
       - containerPort: 8080
