apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: identidock
spec: 
  containers: 
    - image: guillierf/identidock
      name: web
      env:
        - name: "ENV"
          value: "DEV"
      ports: 
       - containerPort: 5000
