apiVersion: v1
kind: Pod
metadata:
  name: identidock
  labels:
    name: web
    app: identidock
spec: 
  containers: 
    - image: guillierf/identidock
      name: identidock
      ports: 
- containerPort: 5000
